import Aircraft from "./Aircraft";
import Airline from "./Airline";
import Airport from "./Airport";
import { PirepRoute } from "./PirepRoute";
import { PirepStatus } from "./PirepStatus";
import { User } from "./User";

export interface Pirep {
  id: string;
  callsign: string;
  flightNumber: string;
  estimatedFuel: number;
  blockFuel: number;
  estminatedAirDistance: number;
  airDistance: number;
  passangers: number;
  estimatedFlightTime: number;
  flightTime: number;
  takeoffTime: Date;
  landingTime: Date;
  dx_rmk: string;
  flightplanText: string;
  routeText: string;
  remarks: string;
  est_zfw: number;
  est_tow: number;
  orig_metar: string;
  orig_taf: string;
  dest_metar: string;
  dest_taf: string;
  altn_metar: string;
  altn_taf: string;
  pilot_notes: string;
  plan_html: string;
  originId: string;
  destinationId: string;
  pilotId: string;
  route?: PirepRoute[];
  pilot?: User;
  airlineId: string;
  airline?: Airline;
  origin?: Airport;
  destination?: Airport;
  aircraftId: string;
  aircraft?: Aircraft;
  status: PirepStatus;
  zfw: number;
  tow: number;
  units: string;
}
