# build environment
FROM node:18-alpine3.14 as build
WORKDIR /app
COPY . .
RUN npm install
WORKDIR /app/frontend
RUN npm install --force
RUN CI=false npx craco build

# production environment
FROM nginx:stable-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY frontend/nginx/nginx.conf /etc/nginx/conf.d
COPY --from=build /app/frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]