export enum EventsType {
  SEND_TOKEN = 'SEND_TOKEN',
  SEND_DOWNLOAD_STATUS = 'SEND_DOWNLOAD_STATUS',
  SEND_DOWNLOAD_PROGRESS = 'SEND_DOWNLOAD_PROGRESS',
  CHECK_IS_UPDATE = 'CHECK_IS_UPDATE',
  CLOSE_APPLICATION = 'CLOSE_APPLICATION',
  MINIMALIZE_APPLICATION = 'MINIMALIZE_APPLICATION',
  CHECK_SIM_STATUS = 'CHECK_SIM_STATUS',
}
